# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrib', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucid.Character')),
            ],
        ),
        migrations.CreateModel(
            name='PlotPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyName', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date Created')),
            ],
        ),
        migrations.AddField(
            model_name='plotpoints',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucid.Story'),
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lucid.Story'),
        ),
    ]
