# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlotPoints',
            new_name='PlotPoint',
        ),
    ]
